#cloud-config
ssh_pwauth: ${ssh_enable_password}

chpasswd:
  expire: false
  users:
    - name: root
      password: ${ssh_root_password}
      type: text

runcmd:
  - sed -i 's/^#\?PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
  - sed -i 's/^#\?PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
  - systemctl restart ssh
