#cloud-config
ssh_pwauth: ${ssh_enable_password}

%{ if node_name == "node4" ~}
package_update: true
packages:
  - apache2
%{ endif ~}

chpasswd:
  expire: false
  users:
    - name: root
      password: ${ssh_root_password}
      type: text

runcmd:
  - sed -i 's/^#\?PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
  - sed -i 's/^#\?PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
  - systemctl restart ssh
%{ if node_name == "node4" ~}
  - systemctl enable --now apache2
%{ endif ~}
